In [4]:
import scipy
import numpy as np

In [20]:
A = np.array([[2, 5, 8, 7], [5, 2, 2, 8], [7, 5, 6, 6], [5, 4, 4, 8]])

LU Factorization or PLU.

In [8]:
from scipy.linalg import lu

In [9]:
p, l, u = lu(A)

In [10]:
p

array([[0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.]])

In [11]:
l

array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.28571429,  1.        ,  0.        ,  0.        ],
       [ 0.71428571,  0.12      ,  1.        ,  0.        ],
       [ 0.71428571, -0.44      , -0.46153846,  1.        ]])

In [12]:
u

array([[ 7.        ,  5.        ,  6.        ,  6.        ],
       [ 0.        ,  3.57142857,  6.28571429,  5.28571429],
       [ 0.        ,  0.        , -1.04      ,  3.08      ],
       [ 0.        ,  0.        ,  0.        ,  7.46153846]])

In [14]:
p @ l @ u - A

array([[ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
       [-8.8817842e-16,  0.0000000e+00,  4.4408921e-16,  0.0000000e+00],
       [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
       [-8.8817842e-16,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00]])

QR Factorization

In [15]:
np.random.seed(seed=0)
B = np.random.randint(10, size = (5,3))
B

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [16]:
from scipy.linalg import qr

In [21]:
q, r = qr(A)

In [22]:
q

array([[-0.19706586,  0.90335743,  0.30027547,  0.23440362],
       [-0.49266464, -0.41826686,  0.45924483,  0.6094494 ],
       [-0.68973049, -0.02474952,  0.17074487, -0.70321085],
       [-0.49266464,  0.09157322, -0.81839784,  0.28128434]])

In [23]:
r

array([[-10.14889157,  -7.38996959,  -8.67089765, -13.40047818],
       [  0.        ,   3.92279868,   6.60812144,   3.56145571],
       [  0.        ,   0.        ,   1.07157127,   0.25317343],
       [  0.        ,   0.        ,   0.        ,   4.54743014]])

In [28]:
np.dot(q[:,0], q[:,1])

-1.3183898417423734e-16

In [29]:
q[:,0] @ q[:,1] # columns of q are orthoganal

-1.3183898417423734e-16

In [31]:
q[:,1] @ q[:,2]

1.249000902703301e-16

In [32]:
q[:,0] @ q[:,0] # columns also normal so othonormal

1.0000000000000002

Symmetric matrix $S=Q\Lambda Q^T$

In [33]:
N = 5
c = np.random.randint(10,size=(N,N))
c_symm = (c + c.T)/2
c_symm

array([[6. , 6. , 5. , 5. , 2. ],
       [6. , 9. , 4. , 6. , 3.5],
       [5. , 4. , 3. , 6.5, 3.5],
       [5. , 6. , 6.5, 1. , 1.5],
       [2. , 3.5, 3.5, 1.5, 1. ]])