In [2]:
import numpy as np
import math

In [9]:
A = np.array([1 + 3j, 2 - 2j, 3, 5 - 7j]).reshape(2,2)
A

array([[1.+3.j, 2.-2.j],
       [3.+0.j, 5.-7.j]])

In [11]:
q, r = np.linalg.qr(A)

In [12]:
q

array([[-0.22941573-0.6882472j ,  0.56383408+0.39468385j],
       [-0.6882472 +0.j        , -0.58262855+0.43227279j]])

In [13]:
r

array([[-4.35889894+0.j        , -2.52357307+6.65305628j],
       [ 0.        +0.j        , -5.60075183+0.j        ]])

Different ways to multiply matrices or arrays in python

In [16]:
q @ r

array([[1.+3.j, 2.-2.j],
       [3.+0.j, 5.-7.j]])

In [17]:
q.dot(r)

array([[1.+3.j, 2.-2.j],
       [3.+0.j, 5.-7.j]])

In [18]:
np.dot(q,r)

array([[1.+3.j, 2.-2.j],
       [3.+0.j, 5.-7.j]])

In [19]:
r.dot(q)

array([[ 2.73684211-1.57894737j, -3.86332527-6.68751952j],
       [ 3.85470177+0.j        ,  3.26315789-2.42105263j]])

In [20]:
np.matmul(q,r)

array([[1.+3.j, 2.-2.j],
       [3.+0.j, 5.-7.j]])

Spectral theorem

In [23]:
S = np.array([4, 3, 3, 5]).reshape(2,2)
S

array([[4, 3],
       [3, 5]])

In [24]:
Q, R = np.linalg.eig(S)

In [25]:
Q

array([1.45861873, 7.54138127])

In [26]:
R

array([[-0.76301998, -0.6463749 ],
       [ 0.6463749 , -0.76301998]])

In [30]:
R[:,0]

array([-0.76301998,  0.6463749 ])

In [32]:
Q_matrix = np.array([Q[0], 0, 0, Q[1]])
Q_matrix

array([1.45861873, 0.        , 0.        , 7.54138127])

In [33]:
Q_matrix @ R

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 4)