In [1]:
import numpy as np
import math

In [2]:
np.random.seed(seed=0)
A = np.random.randint(10, size = (5,3))
A

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

I want to take $A * A^T$

In [3]:
np.linalg.eig(A.dot(A.transpose())) # I think this works

(array([ 3.74765993e+02,  1.82512898e+01,  4.79827176e+01, -6.53444319e-16,
        -5.60177262e-15]),
 array([[-0.21225332, -0.95484953,  0.09958505, -0.12489369,  0.03002575],
        [-0.56724169,  0.00926204, -0.6194619 , -0.15467747,  0.41739322],
        [-0.31008733,  0.24689917,  0.13326169, -0.80388888,  0.43380249],
        [-0.51393848,  0.11251445, -0.19265757,  0.53400639, -0.79568304],
        [-0.52239686,  0.12065608,  0.74261306,  0.17051775,  0.05987703]]))

In [4]:
Λ1, U1 = np.linalg.eig(A @ A.transpose()) # this words like above but I like notation better

In [5]:
Λ1, U1

(array([ 3.74765993e+02,  1.82512898e+01,  4.79827176e+01, -6.53444319e-16,
        -5.60177262e-15]),
 array([[-0.21225332, -0.95484953,  0.09958505, -0.12489369,  0.03002575],
        [-0.56724169,  0.00926204, -0.6194619 , -0.15467747,  0.41739322],
        [-0.31008733,  0.24689917,  0.13326169, -0.80388888,  0.43380249],
        [-0.51393848,  0.11251445, -0.19265757,  0.53400639, -0.79568304],
        [-0.52239686,  0.12065608,  0.74261306,  0.17051775,  0.05987703]]))

In [6]:
Λ2, U2 = np.linalg.eig(A.transpose() @ A)

In [7]:
Λ2, U2

(array([374.76599263,  18.25128978,  47.98271759]),
 array([[-0.51284918, -0.60635883, -0.60771267],
        [-0.68691355,  0.71443602, -0.13315757],
        [-0.51491309, -0.34915631,  0.78291403]]))

In [8]:
U, S, Vh = np.linalg.svd(A)

In [9]:
U

array([[-0.21225332, -0.09958505,  0.95484953,  0.01530755, -0.18182245],
       [-0.56724169,  0.6194619 , -0.00926204, -0.49002922,  0.23300087],
       [-0.31008733, -0.13326169, -0.24689917, -0.22348396, -0.88044471],
       [-0.51393848,  0.19265757, -0.11251445,  0.82787418, -0.0267421 ],
       [-0.52239686, -0.74261306, -0.12065608, -0.15593687,  0.36980152]])

In [10]:
S

array([19.35887374,  6.92695587,  4.27215283])

In [11]:
Vh

array([[-0.51284918, -0.68691355, -0.51491309],
       [-0.60771267, -0.13315757,  0.78291403],
       [ 0.60635883, -0.71443602,  0.34915631]])

The $\Lambda$s and $S^T * S$ all the same - eigenvalues

In [12]:
Λ1[0:3] - Λ2

array([-1.13686838e-13, -2.84217094e-14, -1.42108547e-14])

In [13]:
Λ2 - S.dot(S)

array([ -66.23400737, -422.74871022, -393.01728241])

And the U's, the eigenvectors for $A * A^T$ and $A^T * A$, and U and Vh.

In [19]:
U1 - U # expecting near zero, but not all???

array([[-5.55111512e-17, -8.55264479e-01, -8.55264479e-01,
        -1.40201245e-01,  2.11848196e-01],
       [ 2.22044605e-16, -6.10199863e-01, -6.10199863e-01,
         3.35351746e-01,  1.84392347e-01],
       [-2.22044605e-16,  3.80160855e-01,  3.80160855e-01,
        -5.80404914e-01,  1.31424720e+00],
       [-3.33066907e-16, -8.01431163e-02, -8.01431163e-02,
        -2.93867795e-01, -7.68940940e-01],
       [ 0.00000000e+00,  8.63269137e-01,  8.63269137e-01,
         3.26454613e-01, -3.09924484e-01]])

In [23]:
U2 - Vh.transpose()

array([[-2.22044605e-16,  1.35383227e-03, -1.21407150e+00],
       [ 1.11022302e-16,  8.47593598e-01,  5.81278449e-01],
       [-5.55111512e-16, -1.13207034e+00,  4.33757713e-01]])

In [16]:
U1, U, U2, Vh

(array([[-0.21225332, -0.95484953,  0.09958505, -0.12489369,  0.03002575],
        [-0.56724169,  0.00926204, -0.6194619 , -0.15467747,  0.41739322],
        [-0.31008733,  0.24689917,  0.13326169, -0.80388888,  0.43380249],
        [-0.51393848,  0.11251445, -0.19265757,  0.53400639, -0.79568304],
        [-0.52239686,  0.12065608,  0.74261306,  0.17051775,  0.05987703]]),
 array([[-0.21225332, -0.09958505,  0.95484953,  0.01530755, -0.18182245],
        [-0.56724169,  0.6194619 , -0.00926204, -0.49002922,  0.23300087],
        [-0.31008733, -0.13326169, -0.24689917, -0.22348396, -0.88044471],
        [-0.51393848,  0.19265757, -0.11251445,  0.82787418, -0.0267421 ],
        [-0.52239686, -0.74261306, -0.12065608, -0.15593687,  0.36980152]]),
 array([[-0.51284918, -0.60635883, -0.60771267],
        [-0.68691355,  0.71443602, -0.13315757],
        [-0.51491309, -0.34915631,  0.78291403]]),
 array([[-0.51284918, -0.68691355, -0.51491309],
        [-0.60771267, -0.13315757,  0.78291403],

1,1 element are same but others not.  I'll look into later.