In [3]:
zeros(3,3)

3×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [6]:
rand(3,0) * rand(0,3)

3×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [7]:
ones(3, 3)

3×3 Array{Float64,2}:
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0

In [8]:
function Babylonian(x; N = 10)
    t = (1 + x) / 2
    for i = 2:N; t = (t + x / t) / 2 end
    t
end

Babylonian (generic function with 1 method)

In [11]:
α = π
Babylonian(α), √α

(1.7724538509055159, 1.7724538509055159)

In [13]:
x = 2; Babylonian(x), √x

(1.414213562373095, 1.4142135623730951)

In [12]:
using Plots
plotly()

ArgumentError: ArgumentError: Package Plots not found in current path:
- Run `import Pkg; Pkg.add("Plots")` to install the Plots package.


In [14]:
struct D <: Number # D is a function-derivative pair
    f::Tuple{Float64, Float64}
end

Sum Rule: (x+y)' = x' + y'
Quotient Rule: (x/y)' = (yx'=xy')/y^2

He is going too fast and not show slides for me to copy plus some wrap around

## Heading

$\LaTeX$

# Heading

1 meter x miles/meter x seconds/hour

In [19]:
1 * 0.0006213712 * 3600

2.23693632

1 meter/sec is about 2.24 miles/hour