In [1]:
import numpy as np

In [2]:
?np.random.randint

In [3]:
np.random.rand(3,3)

array([[0.75124846, 0.25854187, 0.14313675],
       [0.16022244, 0.38143896, 0.19030758],
       [0.64800348, 0.25887684, 0.8559113 ]])

In [4]:
A = np.random.randint(10, size = (3,3))
A

array([[9, 5, 1],
       [1, 7, 3],
       [5, 7, 4]])

In [5]:
A_inv = np.linalg.inv(A)
A_inv

array([[ 0.07777778, -0.14444444,  0.08888889],
       [ 0.12222222,  0.34444444, -0.28888889],
       [-0.31111111, -0.42222222,  0.64444444]])

In [6]:
A @ A_inv

array([[ 1.00000000e+00,  1.11022302e-16,  1.11022302e-16],
       [-5.55111512e-17,  1.00000000e+00, -2.22044605e-16],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [7]:
Λ, U = np.linalg.eig(A)

In [8]:
Λ

array([13.2826451 ,  5.48116547,  1.23618944])

In [9]:
U

array([[-0.63463759, -0.81563753,  0.19862963],
       [-0.41293835,  0.57818762, -0.4793902 ],
       [-0.65323583, -0.0208446 ,  0.85482823]])

$Au = \lambda u$

To type greek characters use \ then greek letter spelled out and then tab key.  e.g. \lambda <tab>

In [10]:
u1 = U[:, 0]; u2 = U[:, 1]; u3 = U[:, 2]

In [11]:
λ1 = Λ[0]; λ2 = Λ[1]; λ3 = Λ[2]

In [12]:
A @ u1 # the @ is matrix multiplication I think.

array([-8.42966588, -5.48491351, -8.6766997 ])

In [13]:
A.dot(u1) # can use dot method too - same result.

array([-8.42966588, -5.48491351, -8.6766997 ])

In [14]:
λ1*u1

array([-8.42966588, -5.48491351, -8.6766997 ])

In [20]:
u1.dot(λ1)

array([-8.42966588, -5.48491351, -8.6766997 ])

In [15]:
(A @ u1 == λ1*u1).all()

False

In [16]:
(A @ u2 == λ2*u2).all()

False

In [ ]:
A @ u2 - λ2*u2

In [ ]:
(A @ u3 == λ3*u3).any()

In [ ]:
A @ u3 - λ3*u3 # Very close

#### AB has the same eigen values as BA.  Not same eigen vectors

In [ ]:
A = np.random.randint(10, size = (3,3))
A

In [ ]:
B = np.random.randint(10, size = (3,3))
B

In [ ]:
A @ B

In [ ]:
B @ A

In [ ]:
Λ, U = np.linalg.eig(A @ B)

In [ ]:
Λ

In [ ]:
U

In [ ]:
Λ2, U2 = np.linalg.eig(B @ A)

In [ ]:
Λ2

In [ ]:
U2

In [ ]:
A = np.array([[0, 1], [-1, 0]])
A

In [ ]:
Λ, U = np.linalg.eig(A)

In [ ]:
Λ

In [ ]:
U