# Orthonormal Columns

$Q^T Q = I$


Here and later, I want to be able to quickly create random matrices wheather just regular ones or symmetric or tiagular or dianonal or hermitian or whaterver

In [5]:
A = rand(0:10, 3, 3)

3×3 Array{Int64,2}:
 9  1  1
 0  4  9
 2  6  4

In [1]:
?rand

search: rand randn transcode macroexpand @macroexpand @macroexpand1



```
rand([rng=GLOBAL_RNG], [S], [dims...])
```

Pick a random element or array of random elements from the set of values specified by `S`; `S` can be

  * an indexable collection (for example `1:n` or `['x','y','z']`),
  * an `AbstractDict` or `AbstractSet` object,
  * a string (considered as a collection of characters), or
  * a type: the set of values to pick from is then equivalent to `typemin(S):typemax(S)` for integers (this is not applicable to [`BigInt`](@ref)), and to $[0, 1)$ for floating point numbers;

`S` defaults to [`Float64`](@ref) (except when `dims` is a tuple of integers, in which case `S` must be specified).

# Examples

```julia-repl
julia> rand(Int, 2)
2-element Array{Int64,1}:
 1339893410598768192
 1575814717733606317

julia> rand(MersenneTwister(0), Dict(1=>2, 3=>4))
1=>2
```

!!! note
    The complexity of `rand(rng, s::Union{AbstractDict,AbstractSet})` is linear in the length of `s`, unless an optimized method with constant complexity is available, which is the case for `Dict`, `Set` and `BitSet`. For more than a few calls, use `rand(rng, collect(s))` instead, or either `rand(rng, Dict(s))` or `rand(rng, Set(s))` as appropriate.



Householder matricies
$H = I - 2 * uu^T$ or $H = I - \frac{\nu \nu^T}{\left\| \nu \right\|}$

Strang says we will use these or making orthonormal matrices and that is better than Gram-Schmit.  Chapter 5 of "Matrix Computations", Golub and Van Loan, on Orthogonalization starts off with Householder.

eigenvectors of symmetric, $S^T = S$, and orthogonal, $Q^TQ = I$, are orthogonal.

Discrete Fourier transforms are othogonal vectors.

In [2]:
Q = [0 1 0 0; 0 0 1 0; 0 0 0 1; 1 0 0 0]

4×4 Array{Int64,2}:
 0  1  0  0
 0  0  1  0
 0  0  0  1
 1  0  0  0

In [7]:
Q' * Q

4×4 Array{Int64,2}:
 1  0  0  0
 0  1  0  0
 0  0  1  0
 0  0  0  1

In [10]:
using LinearAlgebra

In [12]:
Q_eig = eigen(Q)

Eigen{Complex{Float64},Complex{Float64},Array{Complex{Float64},2},Array{Complex{Float64},1}}
eigenvalues:
4-element Array{Complex{Float64},1}:
   -1.0000000000000004 + 0.0im               
 8.326672684688674e-17 + 0.9999999999999996im
 8.326672684688674e-17 - 0.9999999999999996im
    0.9999999999999999 + 0.0im               
eigenvectors:
4×4 Array{Complex{Float64},2}:
 -0.5+0.0im  1.38778e-16-0.5im          1.38778e-16+0.5im          -0.5+0.0im
  0.5+0.0im          0.5+1.52656e-16im          0.5-1.52656e-16im  -0.5+0.0im
 -0.5+0.0im   -3.747e-16+0.5im           -3.747e-16-0.5im          -0.5+0.0im
  0.5+0.0im         -0.5+0.0im                 -0.5-0.0im          -0.5+0.0im

In [13]:
Q_eig.values

4-element Array{Complex{Float64},1}:
   -1.0000000000000004 + 0.0im               
 8.326672684688674e-17 + 0.9999999999999996im
 8.326672684688674e-17 - 0.9999999999999996im
    0.9999999999999999 + 0.0im               

looks like maybe -1, i, -i, 1

In [18]:
eig_vals = [-1; im; -im; 1]

4-element Array{Complex{Int64},1}:
 -1 + 0im
  0 + 1im
  0 - 1im
  1 + 0im

In [37]:
λ1 = -1; λ2 = im; λ3 = -im; λ4 = 1

1

In [14]:
Q_eig.vectors

4×4 Array{Complex{Float64},2}:
 -0.5+0.0im  1.38778e-16-0.5im          1.38778e-16+0.5im          -0.5+0.0im
  0.5+0.0im          0.5+1.52656e-16im          0.5-1.52656e-16im  -0.5+0.0im
 -0.5+0.0im   -3.747e-16+0.5im           -3.747e-16-0.5im          -0.5+0.0im
  0.5+0.0im         -0.5+0.0im                 -0.5-0.0im          -0.5+0.0im

In [20]:
eig_vecs = [-0.5 -0.5im 0.5im -0.5; 0.5 0.5 0.5 -0.5; -0.5 0.5im -0.5im -0.5; 0.5 -0.5 -0.5 -0.5]

4×4 Array{Complex{Float64},2}:
 -0.5+0.0im  -0.0-0.5im   0.0+0.5im  -0.5+0.0im
  0.5+0.0im   0.5+0.0im   0.5+0.0im  -0.5+0.0im
 -0.5+0.0im   0.0+0.5im  -0.0-0.5im  -0.5+0.0im
  0.5+0.0im  -0.5+0.0im  -0.5+0.0im  -0.5+0.0im

In [33]:
u1 = eig_vecs[1:4, 1]

4-element Array{Complex{Float64},1}:
 -0.5 + 0.0im
  0.5 + 0.0im
 -0.5 + 0.0im
  0.5 + 0.0im

In [34]:
u2 = eig_vecs[1:4, 2]

4-element Array{Complex{Float64},1}:
 -0.0 - 0.5im
  0.5 + 0.0im
  0.0 + 0.5im
 -0.5 + 0.0im

In [36]:
u3 = eig_vecs[1:4, 3]

4-element Array{Complex{Float64},1}:
  0.0 + 0.5im
  0.5 + 0.0im
 -0.0 - 0.5im
 -0.5 + 0.0im

In [35]:
u4 = eig_vecs[1:4, 4]

4-element Array{Complex{Float64},1}:
 -0.5 + 0.0im
 -0.5 + 0.0im
 -0.5 + 0.0im
 -0.5 + 0.0im

In [40]:
Q * u1 == λ1 * u1

true

In [41]:
Q * u2 == λ2 * u2

true

In [42]:
Q * u3 == λ3 * u3

true

In [43]:
Q * u4 == λ4 * u4

true

In [44]:
u1' * u2

0.0 + 0.0im

In [45]:
u1' * u1

1.0 + 0.0im

In [46]:
u3' * u4

0.0 + 0.0im