# The Four Fundamental Subspaces

## Example 2

In [1]:
import numpy as np
import scipy

In [2]:
B = np.array([[1, -2, -2], [3, -6, -6]])
B

array([[ 1, -2, -2],
       [ 3, -6, -6]])

In [3]:
b = np.array([[0], [0], [0]])
b

array([[0],
       [0],
       [0]])

In [4]:
from scipy.linalg import null_space
from scipy.linalg import orth

Null Space
solutions to $Bx=0$ are 
$x_1 = \begin{bmatrix} 2 \\ 1 \\ 0 \end{bmatrix}$
$x_2 = \begin{bmatrix} 2 \\ 0 \\ 1 \end{bmatrix}$
But these are not prefect vectors to choose since not orthonormal.  These do form bases for null space but not 

So below with null_space from scipy.linalg we get orthonormal basis.

In [7]:
x1 = np.array([[2], [1], [0]])
x2 = np.array([[2], [0], [1]])


In [12]:
x1.transpose() @ x1 # not equal to zero, so not orthogonal 

array([[5]])

In [14]:
B @ x1

array([[0],
       [0]])

In [15]:
B @ x2

array([[0],
       [0]])

In [17]:
ns = null_space(B)
ns

array([[ 0.66666667,  0.66666667],
       [ 0.66666667, -0.33333333],
       [-0.33333333,  0.66666667]])

null space dimension 2 in $\Re^3$ rank of B is 1 and null space dim is m - number of rows.Purple

In [43]:
ns.shape # R^3 with null space dim = 2

(3, 2)

In [28]:
ns[:, 0] @ ns[:, 1] # zero and so are othrogonal.

-5.551115123125783e-17

In [29]:
ns[:, 0] @ ns[:, 0] # one and so normal.

1.0

column space in $\Re^2$ just one dim which is rank, r.

In [30]:
cs = orth(B) # Column space of B
cs

array([[-0.31622777],
       [-0.9486833 ]])

In [39]:
cs.shape[1] # dimension of column space

1

In [41]:
lns = null_space(np.transpose(B)) # left null space
lns

array([[-0.9486833 ],
       [ 0.31622777]])

In [31]:
rs = orth(np.transpose(B))
rs

array([[-0.33333333],
       [ 0.66666667],
       [ 0.66666667]])

In [40]:
rs.shape[1]

1